name: Upload Website

on:
  push:
    branches:
    - Desarrollo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: build
      uses: addnab/docker-run-action@v3
      with: 
        image: node:alpine
        options: -v ${{ github.workspace}}:/react-app
        run: cd /react-app && apk add yarn && yarn add -D webpack-cli && yarn build
       
    - name: check dir
      run: ls 
     
    - name: deploy 
      uses: ./ 
      with:
        args: --follow-symlinks --delete
                  
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
        
        
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2] 
        
    steps:
      - name: Check out Git repositor
        uses: actions/checkout@v1  
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/  
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
         mongodb-version: ${{ matrix.mongodb-version }}
       
      - name: Dependencies
    
        run: npm install
      - name: Install newman
        run: npm install -g newman
      - name: Seed mongo
        run: mongo 127.0.0.1/infinite-digital-postman-tests  test/postman/setup.js
      - name: Run the API and Postman's tests
        run: | 
         npm run start:dev &
         sleep 60
         newman run "frontend.postman_collection.json"
        env:
         MONGO_URI: "mongodb://127.0.0.1:27017/test-db"
         PORT: "3000"
         STAGE: "local"
         NODE_ENV: "develop"

        
        
        
