name: Upload Website

on:
  push:
    branches:
    - Desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: NACHITUY/Frontend-React/action@Desarrollo
    
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS-SESSION-TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        
