name: Upload Website

on:
  push:
    branches:
    - Desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      uses: addnab/docker-run-action@v3
      with: 
        image: node:alpine
        options: -v ${{ github.workspace}}:/react-app
        run: /bin/sh -c "apk add yarn && yarn add -D webpack-cli && yarn run dev" 
    - name: check dirs
      run: ls
         
    - name: sync  
      uses: ./
      with:
        args: --follow-symlinks --delete
                
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
       
        
      
        
        
        
